openapi: 3.2.0
info:
  version: 1.0.0
  title: LucidLink Service API Reference Billing API
  description: The LucidLink API is organized around REST.
servers:
- url: /api/v1
security:
- standard: []
tags:
- name: Billing
  description: Billing operations.
paths:
  /billing/payment:
    x-swagger-router-controller: Billing
    patch:
      tags:
      - Billing
      summary: Set payment details
      operationId: setPaymentDetails
      responses:
        '200':
          description: Success.
        '400':
          description: Invalid request. Check billing model definition.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentDetails'
        description: Payment details to set for the account.
        required: true
    get:
      tags:
      - Billing
      summary: Get payment details
      operationId: getPaymentDetails
      responses:
        '200':
          description: Payment details for the account.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentDetails'
  /billing/current-period:
    x-swagger-router-controller: Billing
    get:
      tags:
      - Billing
      summary: Get details about current billing period
      operationId: getCurrentPeriod
      responses:
        '200':
          description: Details about current billing period.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BillingPeriod'
  /billing/invoices:
    x-swagger-router-controller: Billing
    get:
      tags:
      - Billing
      summary: Get a list of issued invoices
      operationId: getInvoices
      responses:
        '200':
          description: A list of issued invoices.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Invoice'
  /billing/invoices/{id}/breakdown/csv:
    x-swagger-router-controller: Billing
    get:
      tags:
      - Billing
      summary: Retrieve an invoice amount due breakdown by filespace
      operationId: getInvoiceBreakdownPerFilespace
      parameters:
      - name: id
        in: path
        description: ID of the invoice.
        required: true
        schema:
          type: string
      responses:
        '200':
          description: The invoice breakdown per filespace in CSV format.
        '404':
          description: Invoice not found.
          content:
            text/csv:
              schema:
                $ref: '#/components/schemas/NotFound'
components:
  schemas:
    Card:
      required:
      - numberLast4
      - expiryMonth
      - expiryYear
      properties:
        numberLast4:
          type: string
        expiryMonth:
          type: number
        expiryYear:
          type: number
    FilespaceLineItem:
      required:
      - filespace
      - amountDue
      - usageByDimension
      - isDeleted
      - name
      - storageOwner
      properties:
        filespace:
          type: string
          description: Filespace ID
        amountDue:
          type: number
          description: Filespace amount due(fraction of the invoice amount due).
        isDeleted:
          type: boolean
          description: Whether the filespace was deleted during the period or not.
        name:
          type: string
          description: Filespace name.
        storageProvider:
          type: string
        storageOwner:
          type: string
          enum:
          - lucidlink
          - customer
        subscriptionType:
          type: string
          enum:
          - basic
          - teams
          - advanced
          - custom
          - none
        usageByDimension:
          type: array
          items:
            type: object
            $ref: '#/components/schemas/FilespaceUsage'
          example:
          - dimension: ManagedCapacity
            usage: 2048
          - dimension: FilespaceUsers
            usage: 10
    NotFound:
      required:
      - status
      - message
      properties:
        status:
          type: number
          example: 404
        message:
          type: string
    FilespaceLineItemWithForecast:
      allOf:
      - $ref: '#/components/schemas/FilespaceLineItem'
      - properties:
          amountDueForecast:
            description: Filespace amount due forecast
            type: number
        required:
        - amountDueForecast
    FilespaceUsage:
      required:
      - usage
      - dimension
      properties:
        usage:
          type: number
          description: Usage amount.
        dimension:
          type: string
          description: Usage dimension. Based on the billing plan package.
          enum:
          - ManagedCapacity
          - FilespaceUsers
    BadRequest:
      required:
      - status
      - message
      properties:
        status:
          type: number
          example: 400
        message:
          type: string
    BillingPeriod:
      required:
      - start
      - end
      - subscriptionStatus
      - amountDue
      - amountDueForecast
      - currency
      properties:
        start:
          type: number
        end:
          type: number
        subscriptionStatus:
          type: string
        amountDue:
          type: number
          description: Amount due to date within the current period in cents.
        amountDueForecast:
          type: number
          description: Forecast amount due to end of period in cents.
        currency:
          type: string
        trialDays:
          type: number
        filespaceBreakdown:
          type: array
          items:
            type: object
            $ref: '#/components/schemas/FilespaceLineItemWithForecast'
    PaymentDetails:
      properties:
        description:
          type: string
        paymentSourceToken:
          type: string
        card:
          $ref: '#/components/schemas/Card'
    Invoice:
      required:
      - id
      - date
      - lineDescriptions
      - amountDue
      - currency
      - paymentStatus
      - pdfUrl
      - periodStart
      - periodEnd
      properties:
        id:
          type: string
        date:
          type: number
          example: 1549886746000
        lineDescriptions:
          type: array
          items:
            type: string
        amountDue:
          type: number
        currency:
          type: string
        periodStart:
          type: number
        periodEnd:
          type: number
        paymentStatus:
          type: string
          enum:
          - not_paid
          - past_due
          - paid
          - voided
        pdfUrl:
          type: string
        filespaceBreakdown:
          type: array
          items:
            type: object
            $ref: '#/components/schemas/FilespaceLineItem'
  securitySchemes:
    standard:
      type: oauth2
      flows:
        clientCredentials:
          scopes: {}
          tokenUrl: https://auth.lucidlink.com/oauth2/token
