openapi: 3.2.0
info:
  version: 1.0.0
  title: LucidLink Service API Reference Domain API
  description: The LucidLink API is organized around REST.
servers:
- url: /api/v1
security:
- standard: []
tags:
- name: Domain
  description: Domain operations.
paths:
  /domains:
    x-swagger-router-controller: Domain
    post:
      tags:
      - Domain
      summary: Create a domain
      operationId: createDomain
      responses:
        '201':
          description: The domain object that has been created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Domain'
        '400':
          description: Invalid domain name.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '409':
          description: Domain name already taken or account has an existing domain.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Conflict'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Domain'
        description: Domain object to be created. Domains are globally unique across all LucidLink accounts.
        required: true
    get:
      tags:
      - Domain
      summary: Get a list of domains
      operationId: getDomains
      responses:
        '200':
          description: A list of domains.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Domain'
  /domains/{id}:
    x-swagger-router-controller: Domain
    get:
      tags:
      - Domain
      summary: Retrieve a domain
      operationId: getDomain
      parameters:
      - name: id
        in: path
        description: ID of the domain to be retrieved.
        required: true
        schema:
          type: string
      responses:
        '200':
          description: The domain object.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Domain'
        '400':
          description: Invalid domain ID.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '404':
          description: Domain not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
    delete:
      tags:
      - Domain
      summary: Delete a domain
      operationId: deleteDomain
      parameters:
      - in: path
        name: id
        description: ID of the domain to be deleted.
        required: true
        schema:
          type: string
      responses:
        '204':
          description: Success.
        '400':
          description: Invalid domain ID.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '404':
          description: Domain not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
        '409':
          description: Domain has filespaces.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Conflict'
    put:
      tags:
      - Domain
      summary: Update a domain
      operationId: updateDomain
      parameters:
      - in: path
        name: id
        description: ID of the domain to be updated.
        required: true
        schema:
          type: string
      responses:
        '200':
          description: The domain object that has been updated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Domain'
        '400':
          description: Invalid domain name.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequest'
        '404':
          description: Domain not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFound'
        '409':
          description: Domain has filespaces.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Conflict'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Domain'
        description: Domain object to update with.
        required: true
components:
  schemas:
    Conflict:
      required:
      - status
      - message
      properties:
        status:
          type: number
          example: 409
        message:
          type: string
    Domain:
      required:
      - name
      properties:
        id:
          type: string
          readOnly: true
        name:
          description: Lowercase letters, numbers or hyphens. 3-60 chars.
          type: string
    NotFound:
      required:
      - status
      - message
      properties:
        status:
          type: number
          example: 404
        message:
          type: string
    BadRequest:
      required:
      - status
      - message
      properties:
        status:
          type: number
          example: 400
        message:
          type: string
  securitySchemes:
    standard:
      type: oauth2
      flows:
        clientCredentials:
          scopes: {}
          tokenUrl: https://auth.lucidlink.com/oauth2/token
